import type { Project, Profile, NavItem } from './types'

export const PROFILE: Profile = {
  name: 'Rhaine',
  title: 'Graphic Designer',
  location: 'Auckland, NZ',
  tagline:
    'I design clear, confident brands and systems that scale across print + digital.',
  email_user: 'hello',
  email_domain: 'rhaine.anonaddy.com',
  availability: 'Available for work • 2026',
  socials: [{ label: 'LinkedIn', href: '#' }],
  resumeHref: '#',
}

export const PROJECTS: Project[] = [
  {
    id: 'b',
    title: 'Rockshop Campaigns',
    year: '2018-2024',
    category: 'Digital',
    tags: ['Identity', 'Art direction', 'Campaigns', 'Paid social', 'EDMs'],
    summary:
      'In-house design role supporting Aotearoa New Zealand’s leading music retailer, combining long-standing industry heritage with contemporary retail marketing. Responsible for campaign design and execution across paid social, EDMs, web hero assets, print and POS, and photography, delivered across a wide portfolio of global instrument and audio brands.',
    role: 'In-House Designer, Marketing and Campaigns',
    tools: [
      'InDesign',
      'Photoshop',
      'Illustrator',
      'Lightroom',
      'Dreamweaver',
      'Klaviyo',
      'Campaign Monitor',
      'Meta Ads',
      'Wordpress',
      'Magento 2',
      'SilverStripe',
    ],
    coverAlt: 'RS digital identity cover',
    highlights: [
      'Planned, designed, and managed Meta ad campaigns: creative development, budget recommendations, and ongoing optimisation.',
      'Managed end-to-end EDM campaigns (design → build → send), supporting engagement and conversion goals.',
      'Designed and maintained print and in-store POS collateral: catalogues, brochures, stationery, signage, and promotional assets.',
      'Produced photography and videography for community events and product promotions.',
      'Managed marketing schedules, coordinated stakeholders, and consistently delivered to tight deadlines.',
      'Ensured brand consistency and compliance across all channels and touchpoints.',
      'Liaised with printers: reviewed proofs, assessed quotes, and ensured quality, accuracy, and value.',
      'Supported production workflows and implemented process improvements to improve efficiency.',
    ],
    process: [
      {
        label: 'Scope',
        content:
          'Owned design across paid social, EDM, web hero assets, print/POS, and event media, ensuring consistent execution across day-to-day marketing and campaign launches.',
      },
      {
        label: 'Approach',
        content:
          'Built modular templates and a scalable system for fast turnaround. Planned campaign creative, delivered multi-format assets, and maintained a consistent brand standard across channels.',
      },
      {
        label: 'Delivery',
        content:
          'Coordinated stakeholders, managed timelines, and handled print production (proofing, quoting, supplier comms). Captured photo/video content for promotions and supported ongoing optimisation for paid campaigns.',
      },
    ],
    media: [
      {
        id: 'b-edm-1',
        kind: 'image',
        group: 'EDMs',
        src: 'images/projects/b/edm-1.jpg',
        aspect: 'viewport',
      },
      {
        id: 'b-edm-2',
        kind: 'image',
        group: 'EDMs',
        src: 'images/projects/b/edm-2.jpg',
        aspect: 'viewport',
      },
      {
        id: 'b-edm-3',
        kind: 'image',
        group: 'EDMs',
        src: 'images/projects/b/edm-3.jpg',
        aspect: 'viewport',
      },
      {
        id: 'b-edm-4',
        kind: 'image',
        group: 'EDMs',
        src: 'images/projects/b/edm-4.jpg',
        aspect: 'viewport',
      },
      // {
      //   id: 'b-web-1',
      //   kind: 'image',
      //   group: 'Web',
      //   src: 'images/projects/b/web-1.jpg',
      //   aspect: 'auto',
      // },
      // {
      //   id: 'b-web-2',
      //   kind: 'image',
      //   group: 'Web',
      //   src: 'images/projects/b/web-2.jpg',
      //   aspect: 'auto',
      // },
      {
        id: 'b-web-3',
        kind: 'image',
        group: 'Web',
        src: 'images/projects/b/web-3.jpg',
        aspect: 'auto',
      },
      {
        id: 'b-hero-1',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/b/hero-1.jpg',
        alt: 'joe satriani hero guitar transcripts',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-2',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/b/hero-2.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-3',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/b/hero-3.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-4',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/b/hero-4.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-5',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/b/hero-5.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-6',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/b/hero-6.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-7',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/b/hero-7.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-8',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/b/hero-8.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-9',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/b/hero-9.jpg',
        alt: 'joe satriani hero guitar transcripts',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-10',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/b/hero-10.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-11',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/b/hero-11.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-12',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/b/hero-12.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-13',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/b/hero-13.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-14',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/b/hero-14.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-15',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/b/hero-15.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-16',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/b/hero-16.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-ad-1',
        kind: 'image',
        group: 'Social Media Ads',
        src: 'images/projects/b/ad-1.jpg',
        aspect: 'square',
      },
      {
        id: 'b-ad-2',
        kind: 'image',
        group: 'Social Media Ads',
        src: 'images/projects/b/ad-2.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-ad-3',
        kind: 'image',
        group: 'Social Media Ads',
        src: 'images/projects/b/ad-3.jpg',
        aspect: 'banner',
      },
      {
        id: 'b-ad-4',
        kind: 'image',
        group: 'Social Media Ads',
        src: 'images/projects/b/ad-4.jpg',
        aspect: 'auto',
      },
      {
        id: 'b-ad-5',
        kind: 'image',
        group: 'Social Media Ads',
        src: 'images/projects/b/ad-5.jpg',
        aspect: 'auto',
      },
      {
        id: 'b-ad-6',
        kind: 'image',
        group: 'Social Media Ads',
        src: 'images/projects/b/ad-6.jpg',
        aspect: 'auto',
      },
      // {
      //   id: 'b-ad-7',
      //   kind: 'image',
      //   group: 'Social Media Ads',
      //   src: 'images/projects/b/ad-7.jpg',
      //   aspect: 'auto',
      // },
      // {
      //   id: 'b-ad-8',
      //   kind: 'image',
      //   group: 'Social Media Ads',
      //   src: 'images/projects/b/ad-8.jpg',
      //   aspect: 'square',
      // },
      // {
      //   id: 'b-ad-9',
      //   kind: 'image',
      //   group: 'Social Media Ads',
      //   src: 'images/projects/b/ad-9.jpg',
      //   aspect: 'square',
      // },
      {
        id: 'b-ad-10',
        kind: 'image',
        group: 'Social Media Ads',
        src: 'images/projects/b/ad-1.gif',
        aspect: 'square',
      },
      {
        id: 'b-ad-11',
        kind: 'image',
        group: 'Social Media Ads',
        src: 'images/projects/b/ad-2.gif',
        aspect: 'square',
      },
      {
        id: 'b-ad-12',
        kind: 'image',
        group: 'Social Media Ads',
        src: 'images/projects/b/ad-3.gif',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: 'images/projects/b/socials-1.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-2',
        kind: 'image',
        group: 'Socials',
        src: 'images/projects/b/socials-2.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-3',
        kind: 'image',
        group: 'Socials',
        src: 'images/projects/b/socials-3.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-4',
        kind: 'image',
        group: 'Socials',
        src: 'images/projects/b/socials-4.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-5',
        kind: 'image',
        group: 'Socials',
        src: 'images/projects/b/socials-5.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-6',
        kind: 'image',
        group: 'Socials',
        src: 'images/projects/b/socials-6.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-7',
        kind: 'image',
        group: 'Socials',
        src: 'images/projects/b/socials-7.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-8',
        kind: 'image',
        group: 'Socials',
        src: 'images/projects/b/socials-8.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-9',
        kind: 'image',
        group: 'Socials',
        src: 'images/projects/b/socials-9.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-10',
        kind: 'image',
        group: 'Socials',
        src: 'images/projects/b/socials-10.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-11',
        kind: 'image',
        group: 'Socials',
        src: 'images/projects/b/socials-11.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-12',
        kind: 'image',
        group: 'Socials',
        src: 'images/projects/b/socials-12.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-13',
        kind: 'image',
        group: 'Socials',
        src: 'images/projects/b/socials-13.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-14',
        kind: 'image',
        group: 'Socials',
        src: 'images/projects/b/socials-14.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-15',
        kind: 'image',
        group: 'Socials',
        src: 'images/projects/b/socials-15.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-16',
        kind: 'image',
        group: 'Socials',
        src: 'images/projects/b/socials-16.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-17',
        kind: 'image',
        group: 'Socials',
        src: 'images/projects/b/socials-17.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-18',
        kind: 'image',
        group: 'Socials',
        src: 'images/projects/b/socials-18.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-19',
        kind: 'image',
        group: 'Socials',
        src: 'images/projects/b/socials-19.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-20',
        kind: 'image',
        group: 'Socials',
        src: 'images/projects/b/socials-20.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-21',
        kind: 'image',
        group: 'Socials',
        src: 'images/projects/b/socials-21.jpg',
        aspect: 'square',
      },
      // {
      //   id: 'b-social-1',
      //   kind: 'image',
      //   group: 'Preview',
      //   src: 'images/projects/b/socials-preview-1.jpg',
      //   aspect: 'ultrawide',
      // },
      // {
      //   id: 'b-social-2',
      //   kind: 'image',
      //   group: 'Preview',
      //   src: 'images/projects/b/socials-preview-2.jpg',
      //   aspect: 'ultrawide',
      // },
      {
        id: 'b-print-1',
        kind: 'image',
        group: 'Print',
        src: 'images/projects/b/print-1.jpg',
      },
      {
        id: 'b-print-2',
        kind: 'image',
        group: 'Print',
        src: 'images/projects/b/print-2.jpg',
      },
      {
        id: 'b-print-3',
        kind: 'image',
        group: 'Print',
        src: 'images/projects/b/print-3.jpg',
      },
      {
        id: 'b-print-4',
        kind: 'image',
        group: 'Print',
        src: 'images/projects/b/print-4.jpg',
      },
      {
        id: 'b-print-5',
        kind: 'image',
        group: 'Print',
        src: 'images/projects/b/print-5.jpg',
        aspect: 'auto',
      },
      {
        id: 'b-print-6',
        kind: 'image',
        group: 'Print',
        src: 'images/projects/b/print-6.jpg',
        aspect: 'auto',
      },
      {
        id: 'b-print-7',
        kind: 'image',
        group: 'Print',
        src: 'images/projects/b/print-7.jpg',
        aspect: 'auto',
      },
      {
        id: 'b-print-8',
        kind: 'image',
        group: 'Print',
        src: 'images/projects/b/print-8.jpg',
        aspect: 'auto',
      },
      {
        id: 'b-print-9',
        kind: 'image',
        group: 'Print',
        src: 'images/projects/b/print-9.jpg',
        aspect: 'auto',
      },
      {
        id: 'b-print-10',
        kind: 'image',
        group: 'Print',
        src: 'images/projects/b/print-10.jpg',
        aspect: 'auto',
      },
      {
        id: 'b-print-11',
        kind: 'image',
        group: 'Print',
        src: 'images/projects/b/print-11.jpg',
        aspect: 'auto',
      },
      {
        id: 'b-photography-1',
        kind: 'image',
        group: 'Photography',
        src: 'images/projects/b/photo-1.jpg',
        aspect: 'portrait',
      },
      {
        id: 'b-photography-2',
        kind: 'image',
        group: 'Photography',
        src: 'images/projects/b/photo-2.jpg',
        aspect: 'portrait',
      },
      {
        id: 'b-photography-3',
        kind: 'image',
        group: 'Photography',
        src: 'images/projects/b/photo-3.jpg',
        aspect: 'auto',
      },
      {
        id: 'b-photography-4',
        kind: 'image',
        group: 'Photography',
        src: 'images/projects/b/photo-4.jpg',
        aspect: 'auto',
      },
      {
        id: 'b-photography-5',
        kind: 'image',
        group: 'Photography',
        src: 'images/projects/b/photo-5.jpg',
        aspect: 'portrait',
      },
      {
        id: 'b-photography-6',
        kind: 'image',
        group: 'Photography',
        src: 'images/projects/b/photo-6.jpg',
        aspect: 'portrait',
      },
      {
        id: 'b-photography-7',
        kind: 'image',
        group: 'Photography',
        src: 'images/projects/b/photo-7.jpg',
        aspect: 'portrait',
      },
      {
        id: 'b-photography-8',
        kind: 'image',
        group: 'Photography',
        src: 'images/projects/b/photo-8.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-photography-9',
        kind: 'image',
        group: 'Photography',
        src: 'images/projects/b/photo-9.jpg',
        aspect: 'portrait',
      },
      {
        id: 'b-photography-10',
        kind: 'image',
        group: 'Photography',
        src: 'images/projects/b/photo-10.jpg',
        aspect: 'portrait',
      },
      {
        id: 'b-photography-11',
        kind: 'image',
        group: 'Photography',
        src: 'images/projects/b/photography-preview.jpg',
        aspect: 'square',
      },
    ],
  },

  {
    id: 'c',
    title: 'KBB Music Campaigns',
    year: '2018-2024',
    category: 'Digital',
    tags: ['Identity', 'Art direction', 'Campaigns', 'Paid social', 'EDMs'],
    summary:
      'A long-term in-house role providing end-to-end design support for a leading classical musical instrument retailer in Aotearoa New Zealand. The responsibilities covered brand development, campaign design, Meta ad creative, EDMs, print and POS collateral, and photography, supporting consistent delivery across digital, print, and in-store channels.',
    role: 'In-House Designer, Marketing and Campaigns',
    tools: [
      'InDesign',
      'Photoshop',
      'Illustrator',
      'Lightroom',
      'Dreamweaver',
      'Klaviyo',
      'Campaign Monitor',
      'Meta Ads',
      'Wordpress',
      'Magento 2',
      'SilverStripe',
    ],
    links: [
      { label: 'Live site', href: '#' },
      { label: 'Case study PDF', href: '#' },
    ],
    highlights: [
      'Planned, designed, and managed Meta ad campaigns: developed creative concepts, recommended budgets, and iterated assets through ongoing optimisation.',
      'Designed and executed EDM campaigns end-to-end (layout, build, QA), supporting engagement and conversion goals.',
      'Delivered print and in-store POS collateral: catalogues, brochures, signage, and promotional material—kept consistent with brand standards.',
      'Captured and edited photography and videography for community events and product promotions.',
      'Managed marketing schedules, aligned stakeholders, and delivered reliably in a fast-paced environment.',
      'Ensured brand consistency and compliance across digital, print, and in-store touchpoints.',
      'Worked with printers: reviewed proofs, compared quotes, and ensured quality and accuracy.',
      'Improved production workflows through reusable templates and clearer handoff processes.',
    ],
    process: [
      {
        label: 'Challenge',
        content:
          'Maintain a consistent brand presence across fast-moving campaigns and multiple channels while delivering high-quality work on tight timelines.',
      },
      {
        label: 'Approach',
        content:
          'Used a systems-first workflow: created reusable templates and guidelines, designed channel-specific assets (ads, EDMs, print/POS), and ensured consistency across every touchpoint.',
      },
      {
        label: 'Outcome',
        content:
          'A cohesive, scalable marketing system supporting always-on execution—streamlined production, improved consistency, and enabled rapid campaign rollouts across paid, email, web, and in-store.',
      },
    ],
    coverAlt: 'BB brand identity mockups',
    media: [
      {
        id: 'c-print-1',
        kind: 'image',
        group: 'Print',
        src: 'images/projects/c/print-1.jpg',
        alt: 'BB project hero',
        aspect: 'print',
      },
      {
        id: 'c-print-2',
        kind: 'image',
        group: 'Print',
        src: 'images/projects/c/print-2.gif',
        alt: 'BB project hero',
        aspect: 'auto',
      },
      {
        id: 'c-print-3',
        kind: 'image',
        group: 'Print',
        src: 'images/projects/c/print-3.jpg',
        aspect: 'auto',
      },
      {
        id: 'c-print-4',
        kind: 'image',
        group: 'Print',
        src: 'images/projects/c/print-4.jpg',
        aspect: 'auto',
      },
      {
        id: 'c-print-5',
        kind: 'image',
        group: 'Print',
        src: 'images/projects/c/print-5.jpg',
        aspect: 'print',
      },
      {
        id: 'c-print-6',
        kind: 'image',
        group: 'Print',
        src: 'images/projects/c/print-6.jpg',
        aspect: 'print',
      },
      {
        id: 'c-web-1',
        kind: 'image',
        group: 'Web',
        src: 'images/projects/c/web-1.jpg',
        aspect: 'auto',
      },
      // {
      //   id: 'c-web-2',
      //   kind: 'image',
      //   group: 'Web',
      //   src: 'images/projects/c/web-2.jpg',
      //   aspect: 'wide',
      // },
      // {
      //   id: 'c-web-3',
      //   kind: 'image',
      //   group: 'Web',
      //   src: 'images/projects/c/web-3.jpg',
      //   aspect: 'wide',
      // },
      {
        id: 'c-edm-1',
        kind: 'image',
        group: 'EDMs',
        src: 'images/projects/c/edm-1.jpg',
        aspect: 'viewport',
      },
      {
        id: 'c-edm-2',
        kind: 'image',
        group: 'EDMs',
        src: 'images/projects/c/edm-2.jpg',
        aspect: 'viewport',
      },
      {
        id: 'c-edm-3',
        kind: 'image',
        group: 'EDMs',
        src: 'images/projects/c/edm-3.jpg',
        aspect: 'viewport',
      },
      // {
      //   id: 'c-edm-4',
      //   kind: 'image',
      //   group: 'EDMs',
      //   src: 'images/projects/c/edm-4.jpg',
      //   aspect: 'viewport',
      // },
      {
        id: 'c-ad-1',
        kind: 'image',
        group: 'Preview',
        src: 'images/projects/c/ad-1.jpg',
        aspect: 'wide',
      },
      {
        id: 'c-ad-2',
        kind: 'image',
        group: 'Social Media Ads',
        src: 'images/projects/c/ad-2.gif',
        aspect: 'square',
      },
      {
        id: 'c-ad-3',
        kind: 'image',
        group: 'Social Media Ads',
        src: 'images/projects/c/ad-3.jpg',
        aspect: 'square',
      },
      {
        id: 'c-ad-4',
        kind: 'image',
        group: 'Social Media Ads',
        src: 'images/projects/c/ad-4.jpg',
        aspect: 'auto',
      },

      {
        id: 'b-hero-3',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-3.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-hero-4',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-4.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-hero-5',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-5.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-hero-6',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-6.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-hero-7',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-7.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-hero-8',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-8.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-hero-9',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-9.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-hero-10',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-10.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-hero-11',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-11.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-hero-12',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-12.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-hero-13',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-13.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-hero-14',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-14.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-hero-15',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-15.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-hero-16',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-16.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-hero-17',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-17.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-hero-18',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-18.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-hero-19',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-19.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-hero-20',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-20.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-hero-21',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-21.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-hero-22',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-22.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-hero-1',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-1.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-hero-2',
        kind: 'image',
        group: 'Heroes',
        src: 'images/projects/c/hero-2.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'c-photography-1',
        kind: 'image',
        group: 'Photography',
        src: 'images/projects/c/photo-1.jpg',
        aspect: 'wide',
      },
      // {
      //   id: 'c-photography-2',
      //   kind: 'image',
      //   group: 'Photography',
      //   src: 'images/projects/c/photo-2.jpg',
      //   aspect: 'wide',
      // },
    ],
  },

  {
    id: 'g',
    title: 'Neil McNerney Business Card',
    year: '2018',
    category: 'Branding',
    tags: ['Identity', 'Branding'],
    summary:
      'A logo and business card design developed for a Canadian-based counsellor, created to convey trust, guidance, and calm through a strong, symbolic concept.',
    role: 'Lead Designer',
    tools: ['Illustrator'],
    coverAlt: 'RS digital identity cover',
    highlights: [
      'Developed a logo concept based on guidance and reassurance',
      'Designed a high-contrast business card suited to print production',
      'Balanced symbolism with clarity and professionalism',
      'Delivered a practical, real-world brand asset for a service-based business',
    ],
    process: [
      {
        label: 'Challenge',
        content:
          'Design a logo that incorporated a lighthouse motif on a dark background, while ensuring the identity felt professional, approachable, and appropriate for a counselling practice.',
      },
      {
        label: 'Approach',
        content:
          'Translated the lighthouse requirement into a clear, symbolic mark representing guidance, safety, and support. Focused on strong contrast and restraint to ensure clarity, legibility, and versatility across print materials, with the business card acting as a primary real-world touchpoint.',
      },
      {
        label: 'Outcome',
        content:
          'A distinctive, meaningful identity that aligned with the client’s values and worked effectively in print, providing a confident and professional presence for client-facing materials.',
      },
    ],
    media: [
      {
        id: 'f s-print-1',
        kind: 'image',
        group: 'Print',
        src: 'images/projects/g/image-1.jpg',
        aspect: 'auto',
      },
      {
        id: 'f-print-3',
        kind: 'image',
        group: 'Print',
        src: 'images/projects/g/image-2.jpg',
        aspect: 'auto',
      },
    ],
  },

  {
    id: 'a',
    title: 'TailTrail Web App (Prototype)',
    year: '2025',
    category: 'Digital',
    tags: ['Web app', 'Frontend', 'Backend', 'Maps', 'Auth'],
    summary:
      'A full-stack web application that helps reunite lost pets with their owners. Users can report lost or found pets, view nearby pet sightings on an interactive map, and browse recent cases. Built with modern technologies like React, TypeScript, Node.js, and Google Maps API.',
    role: 'Git Keeper',
    tools: ['VS Code', 'Postman', 'React', 'TypeScript', 'Tailwind CSS'],
    links: [
      { label: 'Live site', href: '#' },
      { label: 'Case study PDF', href: '#' },
    ],
    highlights: [
      'Interactive Google Map with custom styling',
      'Submit lost or found pet reports via form',
      'Filter pets by status (Lost / Found / All)',
      'View recent pet sightings in real-time',
      'Auth0 authentication (Sign in / Sign out)',
      'Beautiful responsive UI styled with TailwindCSS',
    ],
    process: [
      {
        label: 'Challenge',
        content:
          'As a team, we set out to design and build a web application to help reunite lost pets with their owners. The challenge was handling real world complexity such as incomplete data, location based reporting, and emotionally stressed users, while delivering an interface that felt simple, reliable, and easy to use on both desktop and mobile.',
      },
      {
        label: 'Approach',
        content:
          'We worked collaboratively to define the core user flows, including reporting lost or found pets, browsing recent sightings, and viewing results on an interactive map. My contribution focused on back end development, supporting the team with API design and server-side logic for creating and retrieving pet reports, filtering results, and integrating authentication. I worked closely with teammates to align data models and request formats with the front end and ensure a smooth handoff between the API and UI.',
      },

      {
        label: 'Outcome',
        content:
          'The team delivered a fully responsive web application that allows users to submit reports, filter sightings, and view nearby results in real time. The project demonstrated strong collaboration across the stack, with reliable back end support for core reporting and discovery features and a shared focus on usability.',
      },
    ],
    coverAlt: 'TailTrail brand image',
    media: [
      {
        id: 'a-preview-1',
        kind: 'video',
        group: 'Preview',
        src: 'images/projects/a/video-1.mp4',
        aspect: 'auto',
      },
      {
        id: 'a-web-1',
        kind: 'image',
        group: 'Web',
        src: 'images/projects/a/image-1.jpg',
        aspect: 'auto',
      },
      {
        id: 'a-web-2',
        kind: 'image',
        group: 'Web',
        src: 'images/projects/a/image-2.jpg',
        aspect: 'auto',
      },
      {
        id: 'a-web-3',
        kind: 'image',
        group: 'Web',
        src: 'images/projects/a/image-3.jpg',
        aspect: 'auto',
      },
      {
        id: 'a-web-4',
        kind: 'image',
        group: 'Web',
        src: 'images/projects/a/image-4.jpg',
        aspect: 'auto',
      },
      {
        id: 'a-web-5',
        kind: 'image',
        group: 'Web',
        src: 'images/projects/a/image-5.jpg',
        aspect: 'auto',
      },
      {
        id: 'a-web-6',
        kind: 'image',
        group: 'Web',
        src: 'images/projects/a/image-6.jpg',
        aspect: 'auto',
      },
      {
        id: 'a-web-7',
        kind: 'image',
        group: 'Web',
        src: 'images/projects/a/image-7.jpg',
        aspect: 'auto',
      },
    ],
  },

  {
    id: 'e',
    title: 'Boutique Dog Grooming Website',
    year: '2024',
    category: 'Digital',
    tags: ['Website Design', 'Brand Identity', 'Design System'],
    summary:
      'A playful yet polished website built in Webflow with a flexible CMS and subtle scroll animations to support ongoing updates. Inspired by a vibrant Instagram personality, brought to life through bold pink tones and a cohesive visual system.',
    role: 'Lead Designer',
    tools: ['Webflow', 'Figma', 'Photoshop', 'Illustrator'],
    coverAlt: 'Website',
    highlights: [
      'Designed and built in Webflow',
      'Dynamic, CMS-powered structure for flexible updates',
      'Subtle scroll animations adding movement and personality',
      'Fully responsive, performance-optimised layout',
    ],
    process: [
      {
        label: 'Challenge',
        content:
          'Create a website that captures the brand’s playful personality while maintaining clarity, structure, and ease of use.',
      },
      {
        label: 'Approach',
        content:
          'Explored the visual identity and translated it into a clear site structure, pairing high-fidelity layouts with considered interaction and motion design.',
      },
      {
        label: 'Outcome',
        content:
          'A dynamic, CMS-driven website built in Webflow, featuring scroll-based animations and a cohesive visual system that brings the brand to life.',
      },
    ],
    media: [
      {
        id: 'e-web-1',
        kind: 'image',
        group: 'Web',
        src: 'images/projects/e/web-1.jpg',
        alt: 'screenshot of website',
        aspect: 'auto',
      },
      {
        id: 'e-web-2',
        kind: 'image',
        group: 'Web',
        src: 'images/projects/e/web-2.jpg',
        alt: 'screenshot of website',
        aspect: 'auto',
      },
      {
        id: 'e-web-3',
        kind: 'image',
        group: 'Web',
        src: 'images/projects/e/web-3.jpg',
        alt: 'screenshot of website',
        aspect: 'auto',
      },
    ],
  },

  // {
  //   id: 'f',
  //   title: 'Flyer for Barbershop',
  //   year: '2023',
  //   category: 'Branding',
  //   tags: ['Print', 'Flyer', 'Business Card'],
  //   summary:
  //     'A direct mail flyer created to increase local awareness and drive new client acquisition, balancing clear messaging with a friendly, approachable tone to encourage first-time visits.',
  //   role: 'Lead Designer',
  //   tools: ['Figma', 'Illustrator'],
  //   coverAlt: 'K digital identity cover',
  //   highlights: [
  //     'Designed a direct mail flyer to support local awareness and client acquisition',
  //     'Focused on clarity, approachability, and first-time engagement',
  //     'SSuccessfully contributed to increased new client enquiries and bookings',
  //     'Delivered a print-ready asset suitable for postal distribution',
  //   ],
  //   process: [
  //     {
  //       label: 'Challenge',
  //       content:
  //         'Create a printed marketing piece that would stand out in a mailbox, feel personal rather than promotional, and clearly communicate the barbershop’s offering to potential new clients within the local area.',
  //     },
  //     {
  //       label: 'Approach',
  //       content:
  //         'Developed a concise, friendly layout that balanced imagery and messaging to feel human and approachable. Prioritised clarity and tone over heavy copy, ensuring the flyer was easy to scan while still communicating value and personality.',
  //     },
  //     {
  //       label: 'Outcome',
  //       content:
  //         'The flyer successfully supported new client acquisition, helping drive awareness of the business within the surrounding community and contributing to an increase in first-time bookings following distribution.',
  //     },
  //   ],
  //   media: [
  //     {
  //       id: 'f-print-1',
  //       kind: 'image',
  //       group: 'Print',
  //       src: 'images/projects/f/print-1.jpg',
  //       aspect: 'auto',
  //     },
  //     {
  //       id: 'f-print-2',
  //       kind: 'image',
  //       group: 'Print',
  //       src: 'images/projects/f/cover.jpg',
  //       aspect: 'auto',
  //     },
  //     {
  //       id: 'f-print-3',
  //       kind: 'image',
  //       group: 'Print',
  //       src: 'images/projects/f/print-3.jpg',
  //       aspect: 'auto',
  //     },
  //     {
  //       id: 'f-print-4',
  //       kind: 'image',
  //       group: 'Print',
  //       src: 'images/projects/f/print-4.jpg',
  //       aspect: 'auto',
  //     },
  //   ],
  // },

  {
    id: 'd',
    title: "MdCL's Patreon",
    year: '2020',
    category: 'Illustration',
    tags: ['Illustration'],
    summary:
      'A series of original illustrations created to support a musician’s Patreon account, helping differentiate offerings and make the page more engaging and approachable for potential supporters.',
    role: 'Illustrator / Lead Designer',
    tools: ['Illustrator', 'Photoshop'],
    coverAlt: 'RS digital identity cover',
    highlights: [
      'Created custom illustrations based on the musician to represent membership tiers',
      'Maintained visual consistency across all tier assets',
      'Balanced personality and clarity without visual clutter',
      'Strengthened brand presence through character-based illustration',
    ],
    process: [
      {
        label: 'Challenge',
        content:
          'Create tier visuals that felt personal and reflective of the musician’s identity.',
      },
      {
        label: 'Approach',
        content:
          'Illustrated the musician in a consistent style across tiers, using variation in pose and expression to differentiate levels while keeping the overall system unified and recognisable.',
      },
      {
        label: 'Outcome',
        content:
          'A visually engaging Patreon page where each tier felt distinct yet connected, reinforcing the musician’s personal brand and improving the overall presentation of the membership structure.',
      },
    ],
    media: [
      {
        id: 'd-image-1',
        kind: 'image',
        group: 'Other',
        src: 'images/projects/d/image-1.jpg',
        aspect: 'wide',
      },
      {
        id: 'd-image-2',
        kind: 'image',
        group: 'Other',
        src: 'images/projects/d/image-2.jpg',
        aspect: 'wide',
      },
      {
        id: 'd-image-3',
        kind: 'image',
        group: 'Other',
        src: 'images/projects/d/image-3.jpg',
        aspect: 'wide',
      },
      {
        id: 'd-image-4',
        kind: 'image',
        group: 'Other',
        src: 'images/projects/d/cover.jpg',
        aspect: 'wide',
      },
    ],
  },
]

export const NAV: readonly NavItem[] = [
  { id: 'work', label: 'Work' },
  { id: 'about', label: 'About' },
  { id: 'services', label: 'Services' },
  { id: 'contact', label: 'Contact' },
] as const
