import type { Project, Profile, NavItem } from './types'

export const PROFILE: Profile = {
  name: 'Reach',
  title: 'Graphic Designer',
  location: 'Auckland, NZ',
  tagline:
    'I design clear, confident brands and systems that scale across print + digital.',
  email: 'you@example.com',
  availability: 'Available for freelance • 2026',
  socials: [{ label: 'LinkedIn', href: '#' }],
  resumeHref: '#',
}

export const PROJECTS: Project[] = [
  {
    id: 'a',
    title: 'Tail',
    year: '2025',
    category: 'Other',
    tags: ['Web Deveopment', 'Indentity'],
    summary:
      'A full-stack web application that helps reunite lost pets with their owners. Users can report lost or found pets, view nearby pet sightings on an interactive map, and browse recent cases. Built with modern technologies like React, TypeScript, Node.js, and Google Maps API.',
    role: 'Git Keeper',
    tools: ['React', 'TypeScript', 'Tailwind CSS'],
    links: [
      { label: 'Live site', href: '#' },
      { label: 'Case study PDF', href: '#' },
    ],
    highlights: [
      'Interactive Google Map with custom styling',
      'Submit lost or found pet reports via form',
      'Filter pets by status (Lost / Found / All)',
      'View recent pet sightings in real-time',
      'Auth0 authentication (Sign in / Sign out)',
      'Beautiful responsive UI styled with TailwindCSS',
    ],
    process: [
      {
        label: 'Challenge',
        content:
          'Unify multiple product lines under one brand while keeping room for seasonal releases.',
      },
      {
        label: 'Approach',
        content:
          'Designed a modular system: core mark + variable descriptor, supported by a high-contrast palette and typographic hierarchy.',
      },
      {
        label: 'Outcome',
        content:
          'A cohesive brand kit that works across packaging, signage, and digital templates for quick rollout.',
      },
    ],
    coverAlt: 'Cobalt Roastery brand identity mockups',
    images: [
      '/images/projects/a/image-1.jpg',
      '/images/projects/a/video-1.mp4',
      '/images/projects/a/image-2.jpg',
      '/images/projects/a/image-3.jpg',
      '/images/projects/a/image-4.jpg',
      '/images/projects/a/image-5.jpg',
      '/images/projects/a/image-6.jpg',
      '/images/projects/a/image-7.jpg',
      '/images/projects/a/image-8.jpg',
    ],
    media: [
      {
        id: 'a-preview-1',
        kind: 'video',
        group: 'Preview',
        src: '/images/projects/a/video-1.mp4',
        aspect: 'wide',
      },
      {
        id: 'a-web-1',
        kind: 'image',
        group: 'Web',
        src: '/images/projects/a/image-1.jpg',
        aspect: 'wide',
      },
      {
        id: 'a-web-2',
        kind: 'image',
        group: 'Web',
        src: '/images/projects/a/image-2.jpg',
        aspect: 'wide',
      },
      {
        id: 'a-web-1',
        kind: 'image',
        group: 'Web',
        src: '/images/projects/a/image-3.jpg',
        aspect: 'wide',
      },
      {
        id: 'a-web-1',
        kind: 'image',
        group: 'Web',
        src: '/images/projects/a/image-4.jpg',
        aspect: 'wide',
      },
      {
        id: 'a-web-1',
        kind: 'image',
        group: 'Web',
        src: '/images/projects/a/image-5.jpg',
        aspect: 'wide',
      },
      {
        id: 'a-web-1',
        kind: 'image',
        group: 'Web',
        src: '/images/projects/a/image-6.jpg',
        aspect: 'wide',
      },
      {
        id: 'a-web-1',
        kind: 'image',
        group: 'Web',
        src: '/images/projects/a/image-7.jpg',
        aspect: 'wide',
      },
    ],
  },

  {
    id: 'b',
    title: 'RS',
    year: '2018-2024',
    category: 'Digital',
    tags: [
      'Identity',
      'Art Direction',
      'Meta Advertising',
      'Design System',
      'Photography',
    ],
    summary:
      'An in-house design system supporting always-on marketing across paid social, EDM, print, and in-store environments, designed to scale with frequent campaigns and tight turnaround times.',
    role: 'Lead Designer',
    tools: [
      'InDesign',
      'Photoshop',
      'Illustrator',
      'Lightroom',
      'Dreamweaver',
      'Klaviyo',
      'Campaign Monitor',
      'Meta Ads',
      'Wordpress',
      'Magento 2',
    ],
    coverAlt: 'RS digital identity cover',
    highlights: [],
    process: [],
    media: [
      {
        id: 'b-edm-1',
        kind: 'image',
        group: 'EDMs',
        src: '/images/projects/b/edm-1.jpg',
        aspect: 'viewport',
      },
      {
        id: 'b-edm-2',
        kind: 'image',
        group: 'EDMs',
        src: '/images/projects/b/edm-2.jpg',
        aspect: 'viewport',
      },
      {
        id: 'b-edm-3',
        kind: 'image',
        group: 'EDMs',
        src: '/images/projects/b/edm-3.jpg',
        aspect: 'viewport',
      },
      {
        id: 'b-edm-4',
        kind: 'image',
        group: 'EDMs',
        src: '/images/projects/b/edm-4.jpg',
        aspect: 'viewport',
      },
      {
        id: 'b-hero-1',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/b/hero-1.jpg',
        alt: 'joe satriani hero guitar transcripts',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-2',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/b/hero-2.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-3',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/b/hero-3.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-4',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/b/hero-4.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-5',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/b/hero-5.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-6',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/b/hero-6.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-7',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/b/hero-7.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-8',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/b/hero-8.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-9',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/b/hero-9.jpg',
        alt: 'joe satriani hero guitar transcripts',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-10',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/b/hero-10.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-11',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/b/hero-11.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-12',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/b/hero-12.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-13',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/b/hero-13.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-14',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/b/hero-14.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-15',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/b/hero-15.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-16',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/b/hero-16.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-web-1',
        kind: 'image',
        group: 'Web',
        src: '/images/projects/b/image-1.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-print-1',
        kind: 'image',
        group: 'Print',
        src: '/images/projects/b/print-1.jpg',
      },
      {
        id: 'b-print-2',
        kind: 'image',
        group: 'Print',
        src: '/images/projects/b/print-2.jpg',
      },
      {
        id: 'b-print-3',
        kind: 'image',
        group: 'Print',
        src: '/images/projects/b/print-3.jpg',
      },
      {
        id: 'b-print-4',
        kind: 'image',
        group: 'Print',
        src: '/images/projects/b/print-4.jpg',
      },
      {
        id: 'b-ad-1',
        kind: 'image',
        group: 'Social Media Ads',
        src: '/images/projects/b/ad-1.jpg',
        aspect: 'square',
      },
      {
        id: 'b-ad-2',
        kind: 'image',
        group: 'Social Media Ads',
        src: '/images/projects/b/ad-2.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-ad-3',
        kind: 'image',
        group: 'Social Media Ads',
        src: '/images/projects/b/ad-3.jpg',
        aspect: 'banner',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-8.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-9.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-10.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-12.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-13.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-14.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-15.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-16.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-17.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-18.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-19.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-20.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-21.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-22.jpg',
        aspect: 'square',
      },
      {
        id: 'b-photography-1',
        kind: 'image',
        group: 'Photography',
        src: '/images/projects/b/photo-1.jpg',
        aspect: 'portrait',
      },
      {
        id: 'b-photography-2',
        kind: 'image',
        group: 'Photography',
        src: '/images/projects/b/photo-2.jpg',
        aspect: 'portrait',
      },
      {
        id: 'b-photography-3',
        kind: 'image',
        group: 'Photography',
        src: '/images/projects/b/photo-3.jpg',
        aspect: 'portrait',
      },
      {
        id: 'b-photography-4',
        kind: 'image',
        group: 'Photography',
        src: '/images/projects/b/photo-4.jpg',
        aspect: 'portrait',
      },
      {
        id: 'b-photography-5',
        kind: 'image',
        group: 'Photography',
        src: '/images/projects/b/photo-5.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-photography-6',
        kind: 'image',
        group: 'Photography',
        src: '/images/projects/b/photo-6.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-photography-7',
        kind: 'image',
        group: 'Photography',
        src: '/images/projects/b/photo-7.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-photography-8',
        kind: 'image',
        group: 'Photography',
        src: '/images/projects/b/photo-8.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-photography-9',
        kind: 'image',
        group: 'Photography',
        src: '/images/projects/b/photo-9.jpg',
        aspect: 'portrait',
      },
    ],
  },

  {
    id: 'c',
    title: 'BB',
    year: '2018-2024',
    category: 'Branding',
    tags: ['Identity', 'Art Direction', 'Meta Advertising'],
    summary: 'A classical music brand...',
    role: 'Lead Designer',
    tools: [
      'InDesign',
      'Photoshop',
      'Illustrator',
      'Lightroom',
      'Dreamweaver',
      'Klaviyo',
      'Campaign Monitor',
      'Meta Ads',
      'Wordpress',
      'Magento 2',
    ],
    links: [
      { label: 'Live site', href: '#' },
      { label: 'Case study PDF', href: '#' },
    ],
    highlights: [
      'Created a flexible identity system with 12 modular lockups.',
      'Reduced label SKUs by 30% through a standardized template.',
      'Improved in-store recognition with consistent shelf-blocking.',
    ],
    process: [
      {
        label: 'Challenge',
        content:
          'Unify multiple product lines under one brand while keeping room for seasonal releases.',
      },
      {
        label: 'Approach',
        content:
          'Designed a modular system: core mark + variable descriptor, supported by a high-contrast palette and typographic hierarchy.',
      },
      {
        label: 'Outcome',
        content:
          'A cohesive brand kit that works across packaging, signage, and digital templates for quick rollout.',
      },
    ],
    coverAlt: 'BB brand identity mockups',
    images: [
      '/images/projects/c/image-1.jpg',
      '/images/projects/c/image-2.jpg',
      '/images/projects/c/image-3.jpg',
      '/images/projects/c/image-4.jpg',
      '/images/projects/c/image-5.jpg',
      '/images/projects/c/image-6.jpg',
    ],
    media: [
      {
        id: 'c-print-1',
        kind: 'image',
        group: 'Print',
        src: '/images/projects/c/print-1.jpg',
        alt: 'BB project hero',
        aspect: 'print',
      },
      {
        id: 'c-print-2',
        kind: 'image',
        group: 'Print',
        src: '/images/projects/c/print-2.jpg',
        alt: 'BB project hero',
        aspect: 'auto',
      },
      {
        id: 'c-print-3',
        kind: 'image',
        group: 'Print',
        src: '/images/projects/c/print-3.jpg',
        aspect: 'auto',
      },
      {
        id: 'c-print-4',
        kind: 'image',
        group: 'Print',
        src: '/images/projects/c/print-4.jpg',
        aspect: 'print',
      },
      {
        id: 'c-print-5',
        kind: 'image',
        group: 'Print',
        src: '/images/projects/c/print-5.jpg',
        aspect: 'print',
      },
      {
        id: 'c-print-6',
        kind: 'image',
        group: 'Print',
        src: '/images/projects/c/print-6.jpg',
        aspect: 'print',
      },
      {
        id: 'b-web-1',
        kind: 'image',
        group: 'Web',
        src: '/images/projects/c/image-2.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-edm-1',
        kind: 'image',
        group: 'EDMs',
        src: '/images/projects/c/edm-1.jpg',
        aspect: 'viewport',
      },
      {
        id: 'b-edm-2',
        kind: 'image',
        group: 'EDMs',
        src: '/images/projects/c/edm-2.jpg',
        aspect: 'viewport',
      },
      {
        id: 'b-edm-3',
        kind: 'image',
        group: 'EDMs',
        src: '/images/projects/c/edm-3.jpg',
        aspect: 'viewport',
      },
      {
        id: 'b-edm-4',
        kind: 'image',
        group: 'EDMs',
        src: '/images/projects/c/edm-4.jpg',
        aspect: 'viewport',
      },
      {
        id: 'b-photography-1',
        kind: 'image',
        group: 'Photography',
        src: '/images/projects/c/image-8.jpg',
        aspect: 'portrait',
      },
      {
        id: 'b-photography-2',
        kind: 'image',
        group: 'Photography',
        src: '/images/projects/c/image-9.jpg',
        aspect: 'portrait',
      },
      {
        id: 'b-hero-1',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/c/image-5.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-2',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/c/image-6.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-3',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/c/image-10.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-4',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/c/image-11.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-5',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/c/image-12.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-6',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/c/image-13.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-6',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/c/image-14.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-6',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/c/image-15.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-6',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/c/image-16.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-6',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/c/image-17.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-6',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/c/image-18.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-hero-6',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/c/image-19.jpg',
        aspect: 'ultrawide',
      },
    ],
  },

  {
    id: 'd',
    title: 'Project',
    year: '2025',
    category: 'Digital',
    tags: ['Identity', 'UI', 'Design System'],
    summary:
      'A digital-first identity system designed for clarity, consistency, and scale.',
    role: 'Lead Designer',
    tools: ['Figma', 'Illustrator'],
    coverAlt: 'RS digital identity cover',
    highlights: [],
    process: [],
    images: [
      '/images/projects/d/image-1.jpg',
      '/images/projects/d/image-2.jpg',
      '/images/projects/d/image-3.jpg',
      '/images/projects/d/image-4.jpg',
      '/images/projects/d/image-5.jpg',
      '/images/projects/d/image-6.jpg',
    ],
    media: [
      {
        id: 'd-print-1',
        kind: 'image',
        group: 'Print',
        src: '/images/projects/d/print-1.jpg',
        aspect: 'portrait',
      },
    ],
  },
  {
    id: 'e',
    title: 'Dog Grooming Website',
    year: '2024',
    category: 'Digital',
    tags: ['Website Design', 'Brand Identity', 'Design System'],
    summary:
      'A playful yet polished website built in Webflow with a flexible CMS and subtle scroll animations to support ongoing updates. Inspired by a vibrant Instagram personality, brought to life through bold pink tones and a cohesive visual system.',
    role: 'Lead Designer',
    tools: ['Webflow', 'Figma', 'Photoshop', 'Illustrator'],
    coverAlt: 'Website',
    highlights: [
      'Designed and built in Webflow',
      'Dynamic, CMS-powered structure for flexible updates',
      'Subtle scroll animations adding movement and personality',
      'Fully responsive, performance-optimised layout',
    ],
    process: [
      {
        label: 'Challenge',
        content:
          'Create a website that captures the brand’s playful personality while maintaining clarity, structure, and ease of use.',
      },
      {
        label: 'Approach',
        content:
          'Explored the visual identity and translated it into a clear site structure, pairing high-fidelity layouts with considered interaction and motion design.',
      },
      {
        label: 'Outcome',
        content:
          'A dynamic, CMS-driven website built in Webflow, featuring scroll-based animations and a cohesive visual system that brings the brand to life.',
      },
    ],
    media: [
      {
        id: 'e-web-1',
        kind: 'image',
        group: 'Web',
        src: '/images/projects/e/web-1.jpg',
        alt: 'screenshot of website',
        aspect: 'auto',
      },
      {
        id: 'e-web-2',
        kind: 'image',
        group: 'Web',
        src: '/images/projects/e/web-2.jpg',
        alt: 'screenshot of website',
        aspect: 'auto',
      },
      {
        id: 'e-web-3',
        kind: 'image',
        group: 'Web',
        src: '/images/projects/e/web-3.jpg',
        alt: 'screenshot of website',
        aspect: 'auto',
      },
    ],
  },
  {
    id: 'f',
    title: 'Miscellaneous Print Projects',
    year: '2018-2024',
    category: 'Digital',
    tags: ['Identity', 'UI', 'Design System'],
    summary:
      'A digital-first identity system designed for clarity, consistency, and scale.',
    role: 'Lead Designer',
    tools: ['Figma', 'Illustrator'],
    coverAlt: 'RS digital identity cover',
    highlights: [],
    process: [],
    images: [
      '/images/projects/f/image-1.jpg',
      '/images/projects/f/image-2.jpg',
      '/images/projects/f/image-3.jpg',
      '/images/projects/f/image-4.jpg',
      '/images/projects/f/image-5.jpg',
      '/images/projects/f/image-6.jpg',
    ],
    media: [
      {
        id: 'f-print-1',
        kind: 'image',
        group: 'Print',
        src: '/images/projects/f/print-1.jpg',
        aspect: 'auto',
      },
      {
        id: 'f-print-2',
        kind: 'image',
        group: 'Print',
        src: '/images/projects/f/cover.jpg',
        aspect: 'portrait',
      },
      {
        id: 'f-print-3',
        kind: 'image',
        group: 'Print',
        src: '/images/projects/f/print-3.jpg',
        aspect: 'auto',
      },
      {
        id: 'f-print-4',
        kind: 'image',
        group: 'Print',
        src: '/images/projects/f/print-4.jpg',
        aspect: 'auto',
      },
    ],
  },
]

export const NAV: readonly NavItem[] = [
  { id: 'work', label: 'Work' },
  { id: 'about', label: 'About' },
  { id: 'services', label: 'Services' },
  { id: 'contact', label: 'Contact' },
] as const
