import type { Project, Profile, NavItem } from './types'

export const PROFILE: Profile = {
  name: 'Reach',
  title: 'Graphic Designer',
  location: 'Auckland, NZ',
  tagline:
    'I design clear, confident brands and systems that scale across print + digital.',
  email: 'you@example.com',
  availability: 'Available for freelance • 2026',
  socials: [{ label: 'LinkedIn', href: '#' }],
  resumeHref: '#',
}

export const PROJECTS: Project[] = [
  {
    id: 'a',
    title: 'Tail',
    year: '2025',
    category: 'Other',
    tags: ['Web Deveopment', 'Indentity'],
    summary:
      'A full-stack web application that helps reunite lost pets with their owners. Users can report lost or found pets, view nearby pet sightings on an interactive map, and browse recent cases. Built with modern technologies like React, TypeScript, Node.js, and Google Maps API.',
    role: 'Git Keeper',
    tools: ['React', 'TypeScript', 'Tailwind CSS'],
    links: [
      { label: 'Live site', href: '#' },
      { label: 'Case study PDF', href: '#' },
    ],
    highlights: [
      'Interactive Google Map with custom styling',
      'Submit lost or found pet reports via form',
      'Filter pets by status (Lost / Found / All)',
      'View recent pet sightings in real-time',
      'Auth0 authentication (Sign in / Sign out)',
      'Beautiful responsive UI styled with TailwindCSS',
    ],
    process: [
      {
        label: 'Challenge',
        content:
          'Unify multiple product lines under one brand while keeping room for seasonal releases.',
      },
      {
        label: 'Approach',
        content:
          'Designed a modular system: core mark + variable descriptor, supported by a high-contrast palette and typographic hierarchy.',
      },
      {
        label: 'Outcome',
        content:
          'A cohesive brand kit that works across packaging, signage, and digital templates for quick rollout.',
      },
    ],
    coverAlt: 'Cobalt Roastery brand identity mockups',
    images: [
      '/images/projects/a/image-1.jpg',
      '/images/projects/a/video-1.mp4',
      '/images/projects/a/image-2.jpg',
      '/images/projects/a/image-3.jpg',
      '/images/projects/a/image-4.jpg',
      '/images/projects/a/image-5.jpg',
      '/images/projects/a/image-6.jpg',
      '/images/projects/a/image-7.jpg',
      '/images/projects/a/image-8.jpg',
    ],
    media: [
      {
        id: 'a-preview-1',
        kind: 'video',
        group: 'Preview',
        src: '/images/projects/a/video-1.mp4',
        aspect: 'wide',
      },
      {
        id: 'a-web-1',
        kind: 'image',
        group: 'Web',
        src: '/images/projects/a/image-1.jpg',
        aspect: 'wide',
      },
      {
        id: 'a-web-2',
        kind: 'image',
        group: 'Web',
        src: '/images/projects/a/image-2.jpg',
        aspect: 'wide',
      },
      {
        id: 'a-web-1',
        kind: 'image',
        group: 'Web',
        src: '/images/projects/a/image-3.jpg',
        aspect: 'wide',
      },
      {
        id: 'a-web-1',
        kind: 'image',
        group: 'Web',
        src: '/images/projects/a/image-4.jpg',
        aspect: 'wide',
      },
      {
        id: 'a-web-1',
        kind: 'image',
        group: 'Web',
        src: '/images/projects/a/image-5.jpg',
        aspect: 'wide',
      },
      {
        id: 'a-web-1',
        kind: 'image',
        group: 'Web',
        src: '/images/projects/a/image-6.jpg',
        aspect: 'wide',
      },
      {
        id: 'a-web-1',
        kind: 'image',
        group: 'Web',
        src: '/images/projects/a/image-7.jpg',
        aspect: 'wide',
      },
    ],
  },

  {
    id: 'b',
    title: 'RS',
    year: '2018-2024',
    category: 'Digital',
    tags: [
      'Identity',
      'Art Direction',
      'Meta Advertising',
      'Design System',
      'Photography',
    ],
    summary:
      'An in-house design system supporting always-on marketing across paid social, EDM, print, and in-store environments, designed to scale with frequent campaigns and tight turnaround times.',
    role: 'Lead Designer',
    tools: [
      'InDesign',
      'Photoshop',
      'Illustrator',
      'Lightroom',
      'Dreamweaver',
      'Klaviyo',
      'Campaign Monitor',
      'Meta Ads',
      'Wordpress',
      'Magento 2',
    ],
    coverAlt: 'RS digital identity cover',
    highlights: [],
    process: [],
    images: [
      '/images/projects/b/image-1.jpg',
      '/images/projects/b/image-2.jpg',
      '/images/projects/b/image-3.jpg',
      '/images/projects/b/image-4.jpg',
      '/images/projects/b/image-5.jpg',
      '/images/projects/b/image-6.jpg',
    ],
    media: [
      {
        id: 'a-hero-1',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/b/hero-1.jpg',
        alt: 'joe satriani hero guitar transcripts',
        aspect: 'ultrawide',
      },
      {
        id: 'a-hero-2',
        kind: 'image',
        group: 'Heroes',
        src: '/images/projects/b/hero-2.jpg',
        aspect: 'ultrawide',
      },
      {
        id: 'b-web-1',
        kind: 'image',
        group: 'Web',
        src: '/images/projects/b/image-1.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-print-1',
        kind: 'image',
        group: 'Print',
        src: '/images/projects/b/image-11.jpg',
      },
      {
        id: 'b-ad-1',
        kind: 'image',
        group: 'Social Media Ads',
        src: '/images/projects/b/ad-1.jpg',
        aspect: 'square',
      },
      {
        id: 'b-ad-2',
        kind: 'image',
        group: 'Social Media Ads',
        src: '/images/projects/b/ad-2.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-ad-3',
        kind: 'image',
        group: 'Social Media Ads',
        src: '/images/projects/b/ad-3.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-8.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-9.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-10.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-12.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-13.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-14.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-15.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-16.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-17.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-18.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-19.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-20.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-21.jpg',
        aspect: 'square',
      },
      {
        id: 'b-social-1',
        kind: 'image',
        group: 'Socials',
        src: '/images/projects/b/image-22.jpg',
        aspect: 'square',
      },
      {
        id: 'b-photography-1',
        kind: 'image',
        group: 'Photography',
        src: '/images/projects/b/image-2.jpg',
        aspect: 'portrait',
      },
      {
        id: 'b-photography-2',
        kind: 'image',
        group: 'Photography',
        src: '/images/projects/b/image-3.jpg',
        aspect: 'portrait',
      },
      {
        id: 'b-photography-3',
        kind: 'image',
        group: 'Photography',
        src: '/images/projects/b/image-4.jpg',
        aspect: 'portrait',
      },
      {
        id: 'b-photography-4',
        kind: 'image',
        group: 'Photography',
        src: '/images/projects/b/image-5.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-photography-4',
        kind: 'image',
        group: 'Photography',
        src: '/images/projects/b/image-6.jpg',
        aspect: 'wide',
      },
    ],
  },

  {
    id: 'c',
    title: 'BB',
    year: '2018-2024',
    category: 'Branding',
    tags: ['Identity', 'Art Direction', 'Meta Advertising'],
    summary: 'A classical music brand...',
    role: 'Lead Designer',
    tools: [
      'InDesign',
      'Photoshop',
      'Illustrator',
      'Lightroom',
      'Dreamweaver',
      'Klaviyo',
      'Campaign Monitor',
      'Meta Ads',
      'Wordpress',
      'Magento 2',
    ],
    links: [
      { label: 'Live site', href: '#' },
      { label: 'Case study PDF', href: '#' },
    ],
    highlights: [
      'Created a flexible identity system with 12 modular lockups.',
      'Reduced label SKUs by 30% through a standardized template.',
      'Improved in-store recognition with consistent shelf-blocking.',
    ],
    process: [
      {
        label: 'Challenge',
        content:
          'Unify multiple product lines under one brand while keeping room for seasonal releases.',
      },
      {
        label: 'Approach',
        content:
          'Designed a modular system: core mark + variable descriptor, supported by a high-contrast palette and typographic hierarchy.',
      },
      {
        label: 'Outcome',
        content:
          'A cohesive brand kit that works across packaging, signage, and digital templates for quick rollout.',
      },
    ],
    coverAlt: 'BB brand identity mockups',
    images: [
      '/images/projects/c/image-1.jpg',
      '/images/projects/c/image-2.jpg',
      '/images/projects/c/image-3.jpg',
      '/images/projects/c/image-4.jpg',
      '/images/projects/c/image-5.jpg',
      '/images/projects/c/image-6.jpg',
    ],
    media: [
      {
        id: 'c-print-1',
        kind: 'image',
        group: 'Print',
        src: '/images/projects/c/print-1.jpg',
        alt: 'BB project hero',
        aspect: 'square',
      },
      {
        id: 'c-social-1',
        kind: 'image',
        group: 'Social Media Ads',
        src: '/images/projects/c/image-3.jpg',
        alt: 'BB project hero',
        aspect: 'square',
      },
      {
        id: 'c-social-2',
        kind: 'image',
        group: 'Social Media Ads',
        src: '/images/projects/c/image-4.jpg',
        aspect: 'wide',
      },
      {
        id: 'c-print-1',
        kind: 'image',
        group: 'Print',
        src: '/images/projects/c/image-1.jpg',
        aspect: 'portrait',
      },
      {
        id: 'b-web-1',
        kind: 'image',
        group: 'Web',
        src: '/images/projects/c/image-2.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-photography-1',
        kind: 'image',
        group: 'Photography',
        src: '/images/projects/c/image-8.jpg',
        aspect: 'portrait',
      },
      {
        id: 'b-photography-2',
        kind: 'image',
        group: 'Photography',
        src: '/images/projects/c/image-9.jpg',
        aspect: 'portrait',
      },
      {
        id: 'b-hero-1',
        kind: 'image',
        group: 'Hero',
        src: '/images/projects/c/image-5.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-hero-2',
        kind: 'image',
        group: 'Hero',
        src: '/images/projects/c/image-6.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-hero-3',
        kind: 'image',
        group: 'Hero',
        src: '/images/projects/c/image-10.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-hero-4',
        kind: 'image',
        group: 'Hero',
        src: '/images/projects/c/image-11.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-hero-5',
        kind: 'image',
        group: 'Hero',
        src: '/images/projects/c/image-12.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-hero-6',
        kind: 'image',
        group: 'Hero',
        src: '/images/projects/c/image-13.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-hero-6',
        kind: 'image',
        group: 'Hero',
        src: '/images/projects/c/image-14.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-hero-6',
        kind: 'image',
        group: 'Hero',
        src: '/images/projects/c/image-15.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-hero-6',
        kind: 'image',
        group: 'Hero',
        src: '/images/projects/c/image-16.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-hero-6',
        kind: 'image',
        group: 'Hero',
        src: '/images/projects/c/image-17.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-hero-6',
        kind: 'image',
        group: 'Hero',
        src: '/images/projects/c/image-18.jpg',
        aspect: 'wide',
      },
      {
        id: 'b-hero-6',
        kind: 'image',
        group: 'Hero',
        src: '/images/projects/c/image-19.jpg',
        aspect: 'wide',
      },
    ],
  },

  {
    id: 'd',
    title: 'Project',
    year: '2025',
    category: 'Digital',
    tags: ['Identity', 'UI', 'Design System'],
    summary:
      'A digital-first identity system designed for clarity, consistency, and scale.',
    role: 'Lead Designer',
    tools: ['Figma', 'Illustrator'],
    coverAlt: 'RS digital identity cover',
    highlights: [],
    process: [],
    images: [
      '/images/projects/d/image-1.jpg',
      '/images/projects/d/image-2.jpg',
      '/images/projects/d/image-3.jpg',
      '/images/projects/d/image-4.jpg',
      '/images/projects/d/image-5.jpg',
      '/images/projects/d/image-6.jpg',
    ],
  },
  {
    id: 'e',
    title: 'Project',
    year: '2025',
    category: 'Digital',
    tags: ['Identity', 'UI', 'Design System'],
    summary:
      'A digital-first identity system designed for clarity, consistency, and scale.',
    role: 'Lead Designer',
    tools: ['Figma', 'Illustrator'],
    coverAlt: 'RS digital identity cover',
    highlights: [],
    process: [],
    images: [
      '/images/projects/e/image-1.jpg',
      '/images/projects/e/image-2.jpg',
      '/images/projects/e/image-3.jpg',
      '/images/projects/e/image-4.jpg',
      '/images/projects/e/image-5.jpg',
      '/images/projects/e/image-6.jpg',
    ],
  },
  {
    id: 'f',
    title: 'Project',
    year: '2025',
    category: 'Digital',
    tags: ['Identity', 'UI', 'Design System'],
    summary:
      'A digital-first identity system designed for clarity, consistency, and scale.',
    role: 'Lead Designer',
    tools: ['Figma', 'Illustrator'],
    coverAlt: 'RS digital identity cover',
    highlights: [],
    process: [],
    images: [
      '/images/projects/f/image-1.jpg',
      '/images/projects/f/image-2.jpg',
      '/images/projects/f/image-3.jpg',
      '/images/projects/f/image-4.jpg',
      '/images/projects/f/image-5.jpg',
      '/images/projects/f/image-6.jpg',
    ],
  },
]

export const NAV: readonly NavItem[] = [
  { id: 'work', label: 'Work' },
  { id: 'about', label: 'About' },
  { id: 'services', label: 'Services' },
  { id: 'contact', label: 'Contact' },
] as const
